os:
  - linux
  - osx

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install: "pip install matplotlib"

env:
  - DC=ldc2
  - DC=dmd

script:
  - dub test --compiler=$DC
